name: CRM Reminder Engine

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd crm_reminder_engine
          pip install -r requirements.txt

      - name: Run reminder engine
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
	  SNEHA_CHAT_ID: ${{ secrets.Sneha_CHAT_ID }}

        run: |
          cd crm_reminder_engine
          python followup_checker.py